spring.application.name=goungue-backend

# Base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/goungue_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Port du serveur (8081 comme pour Shaoume, pour éviter les conflits)
server.port=8082

# Clé secrète pour protéger la création d'admin
setup.secret-key=change-moi-cle-super-secrete-2026
